=== dav0009-byte/1_DAM_dav_LMSG/Tema 10/ejemplo.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (nombre, autor+, editorial?,paginas,precio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== dav0009-byte/1_DAM_dav_LMSG/Tema 10/EjemploTarea3.xml
<?xml version="1.0" encoding="UTF-8" 
standalone="no"?>

<!DOCTYPE biblioteca SYSTEM "./ejemplo.dtd">
<biblioteca>
    <libro>
        <nombre>Introduccion a XML</nombre>
        <autor>Payico payo</autor>
        <editorial>Paranainfo</editorial>
        <paginas>345</paginas>
        <precio>29.95</precio>
    </libro>
    <libro>
        <nombre>CSS3</nombre>
        <autor>Luis ruiz</autor>
        <editorial>Rodrigo payo</editorial>
        <paginas>40000</paginas>
        <precio>3</precio>
    </libro>
</biblioteca>
