=== dav0009-byte/1_DAM_dav_LMSG/Tema11/Ejemplo5/concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <xs:element name="concesionario">
        <xs:complexType>
            <xs:sequence>

            <xs:element name="coche" type="xs:string" maxOccurs ="unbounded"></xs:element>
            <xs:complexType>
                <xs:sequence>

                    <xs:element name="marca" type ="xs:string"></xs:element>
                    <xs:element name ="modelo" type ="xs:string"></xs:element>

                    <xs:choice>

                        <xs:element name="cilindrada" type ="xs:decimal"></xs:element>
                        <xs:element name="caballos" type ="tipoCaballo"></xs:element>

                    </xs:choice>
                    
                    <xs:element name ="combustible" type ="tipoCombustible"></xs:element>
                    <xs:element name="precio" type ="xs:string"></xs:element>
                    <xs:element name ="año" type ="tipoAño" minOccurs="0"></xs:element>
                    <xs:element name ="color" type ="xs:string"></xs:element>
                    <xs:element name="interesados" type = "tipoDni" maxOccurs="unbounded" minOccurs="0"></xs:element>
                    <xs:element name="accesorios" minOccurs ="0" type = "tipoAccesorio"></xs:element>


                     </xs:sequence>  

                        <xs:atribute name="Matricula" type="xs:string" use ="required"></xs:atribute>

                    </xs:sequence>
                </xs:sequence>
            </xs:complexType>

            </xs:sequence>
        </xs:complexType>    
    </xs:element>

        <xs:complexType name ="tipoCombustible">
            <xs:restriction base="xs:string">

                <xs:enumeration value="Diesel"></xs:enumeration>
                <xs:enumeration value="Gasolina"></xs:enumeration>

            </xs:restriction>
        </xs:complexType>
        <xs:complexType name ="tipoCaballo">
            <xs:restriction base="xs:unsignedshort">

                <xs:minInclusive value="60"></xs:minInclusive>
                <xs:maxInclusive value="180"></xs:maxInclusive>

            </xs:restriction>
        </xs:complexType>

        <xs:complexType name="tipoAño">
            <xs:restriction base="insignedShort">

                <xs:totalDigits value="4"></xs:totalDigits>

            </xs:restriction>
        </xs:complexType>

        <xs:simpleType name="tipoDni">
            <xs:restriction base="xs:string">
                <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="tipoAccesorio">
            <xs:list itemType="xs:string"></xs:list>
        </xs:simpleType>

        <xs:simpleType name="tipoAccesorio">
            <xs:restriction base="tipoAccesorio">
                <xs:maxLenght value="3"></xs:maxLenght>
            </xs:restriction>
        </xs:simpleType>
</xs:schema>

=== dav0009-byte/1_DAM_dav_LMSG/Tema11/Ejemplo3/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="concesionario.xsd" provincia="Malaga"></concesionario>


    <coche matricula="6732KPC">
        <marca>Seat</marca>
        <modelo>Ateca</modelo>
        <cilindrada>1.7</cilindrada>
        <combustible>Diesel</combustible>
        <precio>23.000 </precio>
        <año>2018</año>
        <color>negro</color>
        <interesado>33358679A</interesado>
        <interesado>32865901C</interesado>
    </coche>
    <coche matricula="9876ABC">
        <marca>Volksvaguen</marca>
        <modelo>Polo</modelo>
        <cilindrada>1.2</cilindrada>
        <combustible>Gasolina</combustible>
        <precio>5.000 </precio>
        <color>rojo</color>
        <interesado>33358679A</interesado>
    </coche>
